import { useParams, Link } from "react-router-dom";
import { motion } from "motion/react";
import { ArrowLeft, ArrowRight, BookOpen } from "lucide-react";
import Zoom from "react-medium-image-zoom";
import "react-medium-image-zoom/dist/styles.css";
import { articles } from "../data/articles";
import { AdPlaceholder } from "../components/AdPlaceholder";
import { BilingualText } from "../components/BilingualText";
import { useEffect } from "react";

export function Article() {
  const { id } = useParams<{ id: string }>();

  useEffect(() => {
    window.scrollTo(0, 0);
  }, [id]);

  const currentIndex = articles.findIndex((a) => a.id === id);
  const article = articles[currentIndex];

  if (!article) {
    return (
      <div className="max-w-3xl mx-auto px-6 py-20 text-center">
        <h2 className="text-2xl font-bold mb-4">Article Not Found</h2>
        <p className="text-gray-600 mb-8">文章未找到</p>
        <Link to="/" className="text-blue-600 hover:underline">
          Return to Home / 返回首页
        </Link>
      </div>
    );
  }

  const prevArticle = currentIndex > 0 ? articles[currentIndex - 1] : null;
  const nextArticle = currentIndex < articles.length - 1 ? articles[currentIndex + 1] : null;

  const renderContent = () => {
    return article.content.map((paragraph, index) => (
      <motion.div
        key={index}
        initial={{ opacity: 0, y: 20 }}
        whileInView={{ opacity: 1, y: 0 }}
        viewport={{ once: true, margin: "-50px" }}
        transition={{ duration: 0.6, ease: "easeOut" }}
      >
        <BilingualText en={paragraph.en} zh={paragraph.zh} />
      </motion.div>
    ));
  };

  return (
    <article className="max-w-4xl mx-auto px-6 py-12">
      <Link 
        to="/" 
        className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-blue-600 transition mb-10 group"
      >
        <ArrowLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
        Back to Literature / 返回文学列表
      </Link>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="text-center mb-12"
      >
        <h1 className="text-3xl md:text-5xl font-extrabold text-slate-900 leading-tight tracking-tight mb-4">
          {article.titleEn}
        </h1>
        <h2 className="text-2xl md:text-3xl text-slate-600 font-medium">
          {article.titleZh}
        </h2>
        <div className="text-sm text-slate-400 mt-6 tracking-wide uppercase">
          Published / 发布于 {new Date(article.publishDate).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </div>
      </motion.div>

      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ duration: 0.7 }}
        className="w-full mb-16"
      >
        <Zoom>
          <img 
            src={article.coverImage} 
            alt={article.coverImageAltEn} 
            className="w-full aspect-video md:aspect-[21/9] object-cover rounded-2xl bg-slate-100"
          />
        </Zoom>
        <div className="text-center text-xs text-slate-400 mt-3 italic px-4">
          Illustration generated by AI / 人工智能生成的插图
        </div>
      </motion.div>

      {/* Top Ad */}
      <AdPlaceholder className="mb-12" />

      <div className="max-w-2xl mx-auto prose prose-slate prose-lg">
        {renderContent()}
      </div>

      {/* Bottom Ad */}
      <div className="max-w-2xl mx-auto mt-16">
        <AdPlaceholder />
       {/* Article Navigation */}
       <div className="border-t border-slate-200 mt-16 pt-10 border-b pb-10">
          <h3 className="text-xl font-semibold text-slate-800 text-center mb-10 flex items-center justify-center gap-3">
            <BookOpen size={24} className="text-slate-400" />
            Continue Reading / 继续阅读
          </h3>
          <div className="flex flex-col sm:flex-row justify-between items-stretch gap-6">
            {prevArticle ? (
              <Link 
                to={`/article/${prevArticle.id}`}
                className="flex-1 group bg-white rounded-xl p-6 border border-slate-100 shadow-sm hover:shadow-md hover:border-slate-200 transition text-left flex flex-col justify-between"
              >
                <div>
                  <div className="text-xs text-slate-400 font-medium tracking-wide uppercase mb-3 flex items-center gap-1 group-hover:text-blue-600 transition">
                    <ArrowLeft size={14} className="group-hover:-translate-x-1 transition-transform" />
                    Previous / 上一篇
                  </div>
                  <div className="font-semibold text-slate-800 line-clamp-2 md:text-lg mb-1 group-hover:text-blue-700 transition">
                    {prevArticle.titleEn}
                  </div>
                  <div className="text-slate-500 text-sm line-clamp-1 group-hover:text-blue-600/80 transition">
                    {prevArticle.titleZh}
                  </div>
                </div>
              </Link>
            ) : (
               <div className="flex-1" />
            )}

            {nextArticle ? (
              <Link 
                to={`/article/${nextArticle.id}`}
                className="flex-1 group bg-white rounded-xl p-6 border border-slate-100 shadow-sm hover:shadow-md hover:border-slate-200 transition text-right flex flex-col justify-between"
              >
                <div>
                  <div className="text-xs text-slate-400 font-medium tracking-wide uppercase mb-3 flex items-center gap-1 justify-end group-hover:text-blue-600 transition">
                    Next / 下一篇
                    <ArrowRight size={14} className="group-hover:translate-x-1 transition-transform" />
                  </div>
                  <div className="font-semibold text-slate-800 line-clamp-2 md:text-lg mb-1 group-hover:text-blue-700 transition">
                    {nextArticle.titleEn}
                  </div>
                  <div className="text-slate-500 text-sm line-clamp-1 group-hover:text-blue-600/80 transition">
                    {nextArticle.titleZh}
                  </div>
                </div>
              </Link>
            ) : (
                <div className="flex-1" />
            )}
          </div>
        </div>
      </div>

    </article>
  );
}
